spring.application.name=backend


spring.datasource.url=jdbc:mysql://localhost:3306/gymtrack_db
spring.datasource.username=manu
spring.datasource.password=manu
spring.jpa.hibernate.ddl-auto=update

# Seguridad JWT
application.security.jwt.secret-key=VGhpcy1pcy1hLXZlcnktc2VjdXJlLWtleS1mb3Itand0LW11c3QtYmUtYXQtbGVhc3QtMjU2LWJpdHM=
application.security.jwt.expiration=86400000



